### ISSUE TITLE
Script parser doesn't account for optional "run" when running scripts

### ISSUE THREAD

**Issue by jgoux** [webpro-nl/knip#560]
It seems like the script parser doesn't detect scripts when omitting the `run` keyword for package managers like `pnpm` and `yarn`.

In the following Github Action example, the `start:server` script is reported as an unlisted binary:

```yaml
- name: Run dev API in the background background
        run: |
          pnpm -F @snaplet/seed start:server &
          npx --yes wait-on -d 5000 -i 2000 -t 20000 http://localhost:3000 --log --verbose
```

This is fixable by explicitly using `run` like this: ` pnpm -F @snaplet/seed run start:server &`.

But it would be cool if the script parser works without it. 😄
