### ISSUE TITLE
🔄 Production Mode considers dependencies since v5.42.0

### ISSUE THREAD

**Issue by y-yagi** [webpro-nl/knip#914]
### Prerequisites

- [x] I've read the relevant [documentation](https://knip.dev)
- [x] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [x] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://github.com/y-yagi/knip-issue-unlisted-binaries

### Reproduction access

- [x] I've made sure the reproduction is publicly accessible

### Good version

5.42.0 

### Bad version

5.41.1

### Description of the regression

We run the following steps on CI. And, we have `turbo` as `devDependencies`.

```
steps:
  - name: Run knip
    run: pnpm knip --production

  - name: Build
    run: pnpm turbo run build 
``` 

Since v5.42.0, Knip reports `turbo` as `Unlisted binaries`.

```
Unlisted binaries (2)
turbo  .github/workflows/ci.yml 
``` 

I understand the intention, but I could not find any information about these changes in the release notes. So let me ask this change if this is intended or not.
