### ISSUE TITLE
🐛 Fails to parse TypeScript config that comes from npm

### ISSUE THREAD

**Issue by Zamiell** [webpro-nl/knip#964]
### Prerequisites

- [x] I'm using the latest version
- [x] I've read the relevant [documentation](https://knip.dev)
- [x] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [x] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [x] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction access

- [x] I've made sure the reproduction is publicly accessible

### Description of the issue

Hello again, and thanks for the great tool.

I have a GitHub action called [get-package-names](https://github.com/complete-ts/get-package-names). When I use Knip, it says that the "dist/main.js" file is unused, but that is a bug, because it is clearly listed in the "action.yml" file:

```yml
name: get-package-names
description: Gets the packages inside of a monorepo with optional filters

branding:
  icon: package
  color: gray-dark

inputs:
  script-name:
    description: The name of a "package.json" script. If specified, only monorepo packages that contain a script with the specified name will be returned.
    required: false
    default: ""

outputs:
  package-names:
    description: 'The names of the directories that were found in the monorepo "packages" directory. For example: ["foo", "bar"]'

runs:
  using: node20
  main: dist/main.js
```

## Steps To Reproduce

```sh
git clone git@github.com:complete-ts/get-package-names.git
cd get-package-names
git checkout 7e955cf48cae33280c54f14add6aaf8079f022c3
npm ci
npx knip
```
